/*
 * This file is generated by jOOQ.
 */
package com.nova.novademo.codegen.tables.interfaces


import java.io.Serializable
import java.time.LocalDateTime


/**
 * USER TABLE
 */
@Suppress("UNCHECKED_CAST")
interface INovaUser : Serializable {
    var id: String?
    var username: String?
    var email: String?
    var address: String?
    var createTime: LocalDateTime?
    var updateTime: LocalDateTime?
    var deleted: String?

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface INovaUser
     */
    fun from(from: INovaUser)

    /**
     * Copy data into another generated Record/POJO implementing the common interface INovaUser
     */
    fun <E : INovaUser> into(into: E): E
}
