/*
 * This file is generated by jOOQ.
 */
package com.nova.novademo.codegen.tables.references


import com.nova.novademo.codegen.tables.TNovaUser



/**
 * USER TABLE
 */
val NOVA_USER = TNovaUser.NOVA_USER
