/*
 * This file is generated by jOOQ.
 */
package com.nova.novademo.codegen


import kotlin.collections.List

import org.jooq.Schema
import org.jooq.impl.CatalogImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DefaultCatalog : CatalogImpl("") {
    companion object {

        /**
         * The reference instance of <code>DEFAULT_CATALOG</code>
         */
        val DEFAULT_CATALOG = DefaultCatalog()
    }

    /**
     * The schema <code>nova-demo</code>.
     */
    val `NOVA-DEMO` get() = com.nova.novademo.codegen.NovaDemo.`NOVA-DEMO`

    override fun getSchemas(): List<Schema> = listOf(
        com.nova.novademo.codegen.NovaDemo.`NOVA-DEMO`
    )
}
