/*
 * This file is generated by jOOQ.
 */
package com.nova.novademo.codegen


import com.nova.novademo.codegen.tables.TNovaUser

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class NovaDemo : SchemaImpl("nova-demo", DefaultCatalog.DEFAULT_CATALOG) {
    companion object {

        /**
         * The reference instance of <code>nova-demo</code>
         */
        val `NOVA-DEMO` = NovaDemo()
    }

    /**
     * USER TABLE
     */
    val NOVA_USER get() = TNovaUser.NOVA_USER

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        TNovaUser.NOVA_USER
    )
}
